-- =====================================================================
-- V1 — Schéma initial KFOKAM48
-- Dérivé du diagramme de classes (docs/diagrammes/D2_class_diagram.md)
-- et des règles de gestion RG1–RG14.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Promotion et étudiants
-- ---------------------------------------------------------------------
CREATE TABLE promotion (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom   VARCHAR(120) NOT NULL,
    annee INTEGER      NOT NULL,
    CONSTRAINT uk_promotion_nom UNIQUE (nom)
);

CREATE TABLE etudiant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prenom       VARCHAR(80)  NOT NULL,
    nom          VARCHAR(80)  NOT NULL,
    email        VARCHAR(180) NOT NULL,
    promotion_id BIGINT       NOT NULL,
    CONSTRAINT uk_etudiant_email UNIQUE (email),
    CONSTRAINT fk_etudiant_promotion
        FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

-- ---------------------------------------------------------------------
-- Session (EF1, EF11 ; RG1, RG2, RG10, RG14)
-- ---------------------------------------------------------------------
CREATE TABLE session (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre         VARCHAR(150) NOT NULL,
    code          VARCHAR(12)  NOT NULL,
    promotion_id  BIGINT       NOT NULL,
    ouverture_at  TIMESTAMP    NOT NULL,
    expiration_at TIMESTAMP    NOT NULL,
    cloturee      BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_session_code UNIQUE (code),
    CONSTRAINT ck_session_periode CHECK (expiration_at > ouverture_at),
    CONSTRAINT fk_session_promotion
        FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

-- ---------------------------------------------------------------------
-- Présence (EF2, EF10 ; RG2, RG12)
-- ---------------------------------------------------------------------
CREATE TABLE presence (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT       NOT NULL,
    etudiant_id   BIGINT       NOT NULL,
    source        VARCHAR(20)  NOT NULL,
    date_presence TIMESTAMP    NOT NULL,
    -- 409 DEJA_PRESENT
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    CONSTRAINT fk_presence_session
        FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_presence_etudiant
        FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);

-- ---------------------------------------------------------------------
-- Exercice (EF3, EF4, EF5 ; RG5, RG9, RG10, RG11)
-- ---------------------------------------------------------------------
CREATE TABLE exercice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT       NOT NULL,
    etudiant_id BIGINT       NOT NULL,
    lien        VARCHAR(500) NOT NULL,
    statut      VARCHAR(30)  NOT NULL,
    depot_at    TIMESTAMP    NOT NULL,
    -- 409 EXERCICE_DEJA_DEPOSE
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),
    -- nécessaire comme cible de la FK composite de RG4
    CONSTRAINT uk_exercice_id_etudiant UNIQUE (id, etudiant_id),
    CONSTRAINT ck_exercice_statut
        CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'RELU')),
    CONSTRAINT fk_exercice_session
        FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_exercice_etudiant
        FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);

-- ---------------------------------------------------------------------
-- Relecture (EF6, EF7, EF8 ; RG4, RG5, RG6, RG7, RG8)
-- ---------------------------------------------------------------------
CREATE TABLE relecture (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id  BIGINT        NOT NULL,
    relecteur_id BIGINT        NOT NULL,
    -- auteur_id est dénormalisé pour rendre RG4 vérifiable en base
    auteur_id    BIGINT        NOT NULL,
    note         INTEGER,
    commentaire  VARCHAR(2000),
    statut       VARCHAR(20)   NOT NULL,
    rendu_at     TIMESTAMP,
    -- RG5 : un seul relecteur par exercice
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),
    -- RG7 : note entière de 0 à 20
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR (note BETWEEN 0 AND 20)),
    CONSTRAINT ck_relecture_statut CHECK (statut IN ('EN_ATTENTE', 'RENDUE')),
    -- RG4 : aucune auto-relecture
    CONSTRAINT ck_relecture_pas_auto_relecture CHECK (relecteur_id <> auteur_id),
    -- garantit que auteur_id correspond bien à l'auteur de l'exercice
    CONSTRAINT fk_relecture_exercice_auteur
        FOREIGN KEY (exercice_id, auteur_id) REFERENCES exercice (id, etudiant_id),
    CONSTRAINT fk_relecture_relecteur
        FOREIGN KEY (relecteur_id) REFERENCES etudiant (id)
);

-- ---------------------------------------------------------------------
-- Historique des corrections (RG8)
-- ---------------------------------------------------------------------
CREATE TABLE correction_relecture (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relecture_id       BIGINT        NOT NULL,
    ancienne_note      INTEGER       NOT NULL,
    ancien_commentaire VARCHAR(2000),
    corrige_at         TIMESTAMP     NOT NULL,
    CONSTRAINT ck_correction_note CHECK (ancienne_note BETWEEN 0 AND 20),
    CONSTRAINT fk_correction_relecture
        FOREIGN KEY (relecture_id) REFERENCES relecture (id)
);

-- ---------------------------------------------------------------------
-- Tentatives de saisie de code (RG3)
-- ---------------------------------------------------------------------
CREATE TABLE tentative_saisie (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT    NOT NULL,
    etudiant_id   BIGINT    NOT NULL,
    echecs        INTEGER   NOT NULL DEFAULT 0,
    bloque_jusqua TIMESTAMP,
    CONSTRAINT uk_tentative_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_tentative_echecs CHECK (echecs >= 0),
    CONSTRAINT fk_tentative_session
        FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_tentative_etudiant
        FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);

-- ---------------------------------------------------------------------
-- Index (colonnes de jointure et accès fréquents)
-- ---------------------------------------------------------------------
CREATE INDEX idx_etudiant_promotion           ON etudiant (promotion_id);
CREATE INDEX idx_session_promotion_cloturee   ON session (promotion_id, cloturee);
CREATE INDEX idx_presence_session             ON presence (session_id);
CREATE INDEX idx_presence_etudiant            ON presence (etudiant_id);
CREATE INDEX idx_exercice_session             ON exercice (session_id);
CREATE INDEX idx_exercice_etudiant            ON exercice (etudiant_id);
CREATE INDEX idx_relecture_relecteur_statut   ON relecture (relecteur_id, statut);
CREATE INDEX idx_correction_relecture         ON correction_relecture (relecture_id);
CREATE INDEX idx_tentative_session            ON tentative_saisie (session_id);
